### PR TITLE
Add support for V3 Stacks

### LINKED ISSUE #1087: Missing V3 Stacks API
Missing implementation of http://v3-apidocs.cloudfoundry.org/version/3.94.0/#stacks

### PR DESCRIPTION
**Pull request by radito3**
Fixes #1087

### CODE REVIEW

**Comment by radito3** [comment]
Hi @dmikusa-pivotal ,
I have opened the PR in January and am still waiting for the contribution to be accepted in the repository. I would like to ask what else do I have to do for this PR the be accepted?

**Comment by dmikusa-pivotal** [comment]
Hi, sorry for the delay. I took a quick glance and the main thing that jumps out is that there do not appear to be any integration tests. Those would be required before I can merge anything.

It does require full admin access to a CF installation. If you do not have access to one, you can run one locally using bosh-deployment & cf-deployment & Virtualbox.

1. See [Install Section](https://bosh.io/docs/bosh-lite/#install) to install Bosh.
2. Follow the [deployment guide](https://github.com/cloudfoundry/cf-deployment/blob/main/texts/deployment-guide.md#step-4-target-your-bosh-director) to get CF installed. I think you can skip to step 4, since you're installing locally. Definitely [read this section before you get started though](https://github.com/cloudfoundry/cf-deployment/blob/main/texts/deployment-guide.md#for-operators-deploying-cf-to-local-bosh-lite). It has some info for running locally.

If you are unable to do that or unable to write the integration tests, I can write them but I cannot promise priority to that work so it will be much quicker to merge this PR if you are able to provide them. Thanks

**Comment by radito3** [comment]
Hi @dmikusa-pivotal,
I wrote some integration tests. Could you verify them?

**Comment by dmikusa-pivotal** [comment]
I ran the unit & integration tests for this, and they passed. I'm going to merge this. Thanks for the contribution!

**Pull request merged**
