### PR TITLE
Add support to cf-maven-plugin for proxies that require authentication

### PR DESCRIPTION
**Pull request by cgrotz**
I found recently that cf-maven-plugin ignores the username and password settings in the maven proxies. This pull request fixes this issue.

### CODE REVIEW

**Comment by nebhale** [comment]
@cgrotz have you signed the CLA yet?

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.

**Comment by cgrotz** [comment]
I send the contributors agreement today.

**Comment by cgrotz** [comment]
could you please reopen the pull request?

**Pull request closed without merging**
