### PR TITLE
Adding environment variable checks to prevent NPEs on .toString().

### PR DESCRIPTION
**Pull request by MarkHerhold**
This fixes issue #273

### CODE REVIEW

**Comment by scottfrederick** [comment]
Well, that was close. I was just about to press the "release" button to publish 1.1.2 to Maven central when I saw this come in via e-mail. I will merge and test this, then include it in 1.1.2. 

Thanks1

**Comment by MarkHerhold** [comment]
Glad I didn't miss the boat! Thanks!

**Comment by MarkHerhold** [comment]
Can you can ship a release with this fix? I am itching to be able to rely on Maven again!

**Comment by scottfrederick** [comment]
This was included in 1.1.2, which is available in Maven Central now. Releases are typically announced on the CF dev mailing list: https://groups.google.com/a/cloudfoundry.org/d/msg/vcap-dev/aMRQeehu9OY/7LZPWYlw7x4J

**Comment by MarkHerhold** [comment]
@scottfrederick , I ran into the exact issue I patched in v1.1.2. I decompiled the jar and the fix that was merged in simply wasn't present. Can you expedite a v1.1.3 release with this fix in it?

**Pull request merged**
