### PR TITLE
Fix issue #263

### PR DESCRIPTION
**Pull request by andreaturli**
add support for application environment variables

I've completed your CLA Agreement for individuals and just sent at contributors@cloudfoundry.org

### CODE REVIEW

**Comment by jbayer** [comment]
@scottfrederick we've received the CLA from @andreaturli

thanks for your contribution!

**Comment by scottfrederick** [comment]
Thanks @andreaturli, this looks good! 

One request on formatting - please use tabs for indentation on new code to remain consistent with existing code, and avoid re-formatting existing code to replace tabs with spaces. 

Also, most methods that act on applications take the app name as the parameter. To be consistent, we should have a `getAppEnvironment` method that takes the app name, in addition to the one that takes a GUID. 

If you can make these changes and push them to the same fork and branch, the PR will be updated and I will merge it. 

Thanks again for the contribution.

**Comment by andreaturli** [comment]
thanks @scottfrederick I've addressed your comments and added `getApplicationEnvironment(String appName)` with its test. I've also fixed the formatting, I think.

Thanks for your review

If that will be merged, is there a maven repository where I can get the SNAPSHOT?

**Comment by scottfrederick** [comment]
Well, I'm afraid the formatting is worse now :-) Look at this view:
https://github.com/cloudfoundry/cf-java-client/pull/264/files. Now there
are a bunch of unrelated whitespace changes and re-organizing of import
statements that weren't there before, which makes it harder to see what the
real changes were. And it appears the added code still isn't indented the
same as the surrounding code:
https://github.com/cloudfoundry/cf-java-client/pull/264/files#diff-604d152f5bfadf46ec23ac5ce642ed3eR210
.

Can you take one more try at the formatting, trying to fix only the code
that was added or changed?

Unfortunately we don't publish snapshots anywhere right now. I'd like to
publish snapshots and milestones to repo.spring.io but that's another to-do
item.

**Comment by andreaturli** [comment]
Ops sorry, I think now it is better even if my IDE decided to remove some trailing spaces inside the comments. Is it acceptable now?

**Comment by scottfrederick** [comment]
Yeah, that's better. The extra formatting still creates a lot of noise in
the diff that makes it hard to see what the real changes are. It's best not
to let your IDE do re-formatting of existing code when working with code
like this that has lots of history to it. I'll merge this as-is.

**Comment by andreaturli** [comment]
Thanks @scottfrederick, sorry again for the formatting issue.

Is there a roadmap for the new release of `cf-java-client/cloudfoundry-client-lib`?

**Pull request merged**
