### PR TITLE
Filter assign users request on creating organization or space, in ca…

### PR DESCRIPTION
**Pull request by pavellom**
https://github.com/cloudfoundry/cf-java-client/issues/939

### CODE REVIEW

**Comment by pavellom** [comment]
@twoseat, can you review this PR?

**Comment by twoseat** [comment]
Thanks @pavellom, looking at this now.

**Comment by twoseat** [comment]
Hi @pavellom My concern with this PR is that it's not in line with the solution the CLI team have implemented - we shouldn't just be skipping an association, we should be making it based on the uaa id (see the now-fixed links in the original issue for more detail). So while this fix might work for your specific case, it's not a generalisable solution. I'd be interested to hear your thoughts.

**Comment by pavellom** [comment]
Hi @twoseat,

I agree, I've missed the solution provided by cli colleagues.

**Pull request closed without merging**
