### PR TITLE
Added the status of the last operation requested on the service instance

### PR DESCRIPTION
**Pull request by s-bortolussi**
Hello,

Recent Async API enables to retrieve the state of the last operation requested on a service instance (in progress, succeeded or failed).
This pull request proposes to implement such a behavior.

Sebastien

### CODE REVIEW

**Comment by s-bortolussi** [comment]
I have just signed the CLA.

https://github.com/orgs/Orange-OpenSource-Cf/people

**Comment by scottfrederick** [comment]
@s-bortolussi The async service broker API changes are still officially "experimental" in CF, and it is possible that the API could change before this feature is complete. We've decided to hold off on merging this PR until async is complete.

**Comment by gberche-orange** [comment]
@scottfrederick The service broker API async support is now official (cf http://cf-dev.70369.x6.nabble.com/cf-dev-Announcing-Experimental-support-for-Asynchronous-Service-Operations-tp287p1471.html ) 

Can you please resume merge considerations for this PR ?

Thanks,

Guillaume.

**Comment by nebhale** [comment]
This support will be added as part of the V2 effort.  You can track its progress [here](https://www.pivotaltracker.com/story/show/101451546).  Since this was opened against the V1 branch, where we will not be making changes I'm going to close this out.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.

**Pull request closed without merging**
