### PR TITLE
use HttpComponentsClientHttpRequestFactory with HttpClient

### PR DESCRIPTION
**Pull request by robertgmoss**
for connections instead of CustomSslSimpleClientHttpRequestFactory

### CODE REVIEW

**Comment by nebhale** [comment]
@robertgmoss We're actually removing the entire Spring-based network stack this week, to be replaced by a Netty-based one.  I'll leave this PR open until that is done to remind me that I need to test against HTTP endpoints, but I don't foresee this being included.

**Comment by nebhale** [comment]
@robertgmoss What's the use case for accessing HTTP endpoints instead of HTTPS?  We've finished the network stack migration, but it does assume HTTPS only.  Before I modify that, I want to get an idea why you wouldn't always used HTTPS.

**Comment by robertgmoss** [comment]
I don't recall the details, but using the HTTP endpoint fixed an issue we had connecting to our client's CF wherby an SSLException was thrown - an issue that the cli didn't have.  Agree in general HTTPS is better, though.

**Comment by nebhale** [comment]
@robertgmoss We've found some issues here and there in months since this was opened.  Can you have a crack with the latest snapshot and see if an HTTPS-only solution now works for you?

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.

**Pull request closed without merging**
